version: '3.8'

services:
  app1: &app
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app1
    networks:
      - backend
      - payment-processor
    ports:
      - "8003:8080"
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - RABBITMQ_CONNECTION_URL=amqp://user:password@rabbitmq:5672
      - REDIS_CONNECTION_URL=redis://redis-rinha:6379
      - MAX_WORKERS=10
      - MAX_QUEUE=20000
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - rinha-store:/data
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "50MB"

  app2:
    <<: *app
    hostname: app2
    ports:
      - "8004:8080"
    environment:
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - RABBITMQ_CONNECTION_URL=amqp://user:password@rabbitmq:5672
      - REDIS_CONNECTION_URL=redis://redis-rinha:6379
      - MAX_WORKERS=10
      - MAX_QUEUE=20000

  nginx:
    image: nginx:latest
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - backend
    depends_on:
      - app1
      - app2
    deploy:
      resources:
        limits:
          cpus: "0.20"
          memory: "50MB"

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "90MB"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 5s
      timeout: 10s
      retries: 5
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "0.40"
    #       memory: "150MB"

  redis:
    image: redis:latest
    container_name: redis-rinha
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "PING"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  postgres_data:
  rinha-store:
  rabbitmq_data:
  redis_data:

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true